# Use root/example as user/password credentials
version: '3.1'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:65YAJZ+7vuXZgnJvnfyENjA0y4OMacpqmZ0Vuoq8co8=
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
      LOG_CHANNEL: stderr
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: demo
      DB_USERNAME: develop
      DB_PASSWORD: secret
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: null
      MAIL_FROM_NAME:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET:
      PUSHER_APP_ID:
      PUSHER_APP_KEY:
      PUSHER_APP_SECRET:
      PUSHER_APP_CLUSTER: mt1
      MIX_PUSHER_APP_KEY:
      MIX_PUSHER_APP_CLUSTER:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: develop
      POSTGRES_DB: demo
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

